language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN='de64aea2-537d-4092-8f7f-36bd696c46de'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - rail.himax1982@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
